"use client";
import{useState,useEffect,useCallback,useRef}from"react";
import{createClient}from"@/shared/supabase/client";
import{STATUSES,REPAIR_STATUSES,DELIVERY_VISIBLE_FROM,ALL_STATUS_COLORS,PAY_COLORS,CATEGORIES,FINISH_TYPES,WOOD_TYPES,REPAIR_REASONS,CUSTOMER_TYPES,PAYMENT_TERMS,DOC_TYPES,DOC_ICONS,ROLES_CAN_CREATE,ROLES_CAN_EDIT,ROLES_CAN_ADVANCE,ROLES_CAN_ADD_NOTES,ROLES_CAN_UPLOAD,ROLES_CAN_DELIVER,ROLES_CAN_PAY,ROLES_CAN_REPAIR,SALES_MAX_ADVANCE_TO,STATUS_BORDER_CLASS,ss,getPayStatus,getStatusList,genId}from"./constants";

async function logAct(sb,oid,t,d,o,n){await sb.from("order_activities").insert({order_id:oid,activity_type:t,description:d,old_value:o||null,new_value:n||null})}
function Badge({status,type}){const c=(type==="payment"?PAY_COLORS:ALL_STATUS_COLORS)[status]||{bg:"#eee",text:"#333",border:"#ccc"};return <span style={{display:"inline-block",padding:"3px 8px",borderRadius:"4px",fontSize:"10px",fontWeight:700,letterSpacing:"0.3px",textTransform:"uppercase",background:c.bg,color:c.text,border:`1.5px solid ${c.border}`}}>{status}</span>}
function TruncText({text,lines}){const[exp,setExp]=useState(false);if(!text)return null;const st=exp?{}:{display:"-webkit-box",WebkitLineClamp:lines||3,WebkitBoxOrient:"vertical",overflow:"hidden"};return <div><div style={{...st,fontSize:"13px",color:"#333",whiteSpace:"pre-wrap",lineHeight:1.5}}>{text}</div>{text.length>150&&<button onClick={()=>setExp(!exp)} style={{background:"none",border:"none",color:"#1565C0",cursor:"pointer",fontSize:"11px",fontWeight:600,padding:"4px 0"}}>{exp?"Show less":"Show more"}</button>}</div>}

/* === ITEMS BUILDER === */
function ItemsBuilder({items,onChange}){
  const add=()=>onChange([{_id:genId(),category:"Wall Decoration Canvas",description:"",quantity:1,size:"",finish_type:"None",finish_color:"",wood_type:"",unit_price:"",notes:""},...items]);
  const upd=(id,f,v)=>onChange(items.map(i=>i._id===id?{...i,[f]:v}:i));const del=(id)=>onChange(items.filter(i=>i._id!==id));
  return(<div style={{marginTop:"4px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"8px"}}><div style={ss.label}>Order Items</div><button type="button" onClick={add} style={{...ss.btn,background:"#1a1a1a",color:"#fff",fontSize:"12px",padding:"6px 14px"}}>+ Add Item</button></div>
    {items.length===0&&<div style={{fontSize:"12px",color:"#bbb",padding:"16px",textAlign:"center",background:"#fafafa",borderRadius:"6px",border:"1px dashed #ddd"}}>No items yet.</div>}
    {items.map((item,idx)=>(<div key={item._id} style={{background:"#FAFAF8",borderRadius:"10px",border:"1.5px solid #E8E5E0",padding:"12px",marginBottom:"8px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"8px"}}><span style={{fontSize:"12px",fontWeight:700,color:"#999"}}>Item {idx+1}</span><button type="button" onClick={()=>del(item._id)} style={{background:"none",border:"none",color:"#C62828",cursor:"pointer",fontSize:"12px",fontWeight:700}}>Remove</button></div>
      <div className="form-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"8px"}}><div><label style={{...ss.label,fontSize:"10px"}}>Category</label><select value={item.category} onChange={e=>upd(item._id,"category",e.target.value)} style={ss.sm}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div><div><label style={{...ss.label,fontSize:"10px"}}>Qty</label><input type="number" value={item.quantity} onChange={e=>upd(item._id,"quantity",parseInt(e.target.value)||1)} style={ss.sm} min="1"/></div><div><label style={{...ss.label,fontSize:"10px"}}>Size</label><input type="text" value={item.size} onChange={e=>upd(item._id,"size",e.target.value)} placeholder="e.g. 60x40cm" style={ss.sm}/></div><div><label style={{...ss.label,fontSize:"10px"}}>Finish Type</label><select value={item.finish_type} onChange={e=>upd(item._id,"finish_type",e.target.value)} style={ss.sm}>{FINISH_TYPES.map(f=><option key={f}>{f}</option>)}</select></div><div><label style={{...ss.label,fontSize:"10px"}}>Finish Color</label><input type="text" value={item.finish_color} onChange={e=>upd(item._id,"finish_color",e.target.value)} placeholder="e.g. Dark Walnut" style={ss.sm}/></div><div><label style={{...ss.label,fontSize:"10px"}}>Wood Type</label><select value={item.wood_type} onChange={e=>upd(item._id,"wood_type",e.target.value)} style={ss.sm}><option value="">-</option>{WOOD_TYPES.map(w=><option key={w}>{w}</option>)}</select></div><div><label style={{...ss.label,fontSize:"10px"}}>Unit Price (KES)</label><input type="number" value={item.unit_price} onChange={e=>upd(item._id,"unit_price",e.target.value)} style={ss.sm}/></div><div style={{gridColumn:"1 / -1"}}><label style={{...ss.label,fontSize:"10px"}}>Description</label><input type="text" value={item.description||""} onChange={e=>upd(item._id,"description",e.target.value)} placeholder="Details" style={ss.sm}/></div></div></div>))}</div>);
}

/* === ITEMS TABLE === */
function ItemsTable({items}){if(!items||items.length===0)return null;const total=items.reduce((s,i)=>(parseFloat(i.unit_price)||0)*(i.quantity||1)+s,0);
  return(<div style={{marginTop:"14px"}}><div style={ss.label}>Items ({items.length})</div>
    <div className="items-table" style={{overflowX:"auto",marginTop:"6px"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:"12px"}}><thead><tr style={{background:"#f5f5f3",textAlign:"left"}}>{["#","Category","Description","Qty","Size","Finish","Wood","Price"].map(h=><th key={h} style={{padding:"6px 8px",fontWeight:600,color:"#888",fontSize:"10px",textTransform:"uppercase",borderBottom:"1px solid #eee",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{items.map((item,i)=><tr key={item.id||i} style={{borderBottom:"1px solid #f0f0f0"}}><td style={{padding:"6px 8px",color:"#bbb"}}>{i+1}</td><td style={{padding:"6px 8px",fontWeight:600,whiteSpace:"nowrap"}}>{item.category}</td><td style={{padding:"6px 8px",color:"#666",maxWidth:"200px"}}>{item.description||"-"}</td><td style={{padding:"6px 8px",fontWeight:700}}>{item.quantity}</td><td style={{padding:"6px 8px",whiteSpace:"nowrap"}}>{item.size||"-"}</td><td style={{padding:"6px 8px",whiteSpace:"nowrap"}}>{item.finish_type&&item.finish_type!=="None"?<>{item.finish_type}{item.finish_color&&<span style={{color:"#888"}}> - {item.finish_color}</span>}</>:"-"}</td><td style={{padding:"6px 8px",whiteSpace:"nowrap"}}>{item.wood_type||"-"}</td><td style={{padding:"6px 8px",fontWeight:600}}>{parseFloat(item.unit_price)?`KES ${((parseFloat(item.unit_price))*(item.quantity||1)).toLocaleString()}`:"-"}</td></tr>)}</tbody>{total>0&&<tfoot><tr style={{background:"#f5f5f3"}}><td colSpan={7} style={{padding:"6px 8px",fontWeight:700,textAlign:"right",fontSize:"11px"}}>TOTAL</td><td style={{padding:"6px 8px",fontWeight:700}}>KES {total.toLocaleString()}</td></tr></tfoot>}</table></div>
    <div className="items-cards" style={{display:"none",flexDirection:"column",gap:"8px",marginTop:"6px"}}>{items.map((item,i)=><div key={item.id||i} style={{background:"#FAFAF8",borderRadius:"10px",border:"1.5px solid #E8E5E0",padding:"12px"}}><div style={{fontSize:"13px",fontWeight:700,marginBottom:"4px"}}>{item.category}</div>{item.description&&<div style={{fontSize:"12px",color:"#666",marginBottom:"6px"}}>{item.description}</div>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"4px",fontSize:"11px"}}><div><span style={{color:"#888"}}>Qty:</span> <strong>{item.quantity}</strong></div>{item.size&&<div><span style={{color:"#888"}}>Size:</span> {item.size}</div>}{item.finish_type&&item.finish_type!=="None"&&<div><span style={{color:"#888"}}>Finish:</span> {item.finish_type}{item.finish_color?" - "+item.finish_color:""}</div>}{item.wood_type&&<div><span style={{color:"#888"}}>Wood:</span> {item.wood_type}</div>}{parseFloat(item.unit_price)>0&&<div><span style={{color:"#888"}}>Price:</span> <strong>KES {((parseFloat(item.unit_price))*(item.quantity||1)).toLocaleString()}</strong></div>}</div></div>)}{total>0&&<div style={{textAlign:"right",fontSize:"12px",fontWeight:700,padding:"4px 0"}}>Total: KES {total.toLocaleString()}</div>}</div>
  </div>);
}

/* === NOTES === */
function NotesThread({orderId,userRole,userName,orderStatus}){const[notes,setNotes]=useState([]);const[text,setText]=useState("");const[ld,setLd]=useState(true);const sb=createClient();
  const load=useCallback(async()=>{const{data}=await sb.from("order_notes").select("*").eq("order_id",orderId).order("created_at",{ascending:false});setNotes(data||[]);setLd(false)},[orderId]);useEffect(()=>{load()},[load]);
  const add=async()=>{if(!text.trim())return;await sb.from("order_notes").insert({order_id:orderId,content:text.trim(),author_name:userName||"Unknown"});await logAct(sb,orderId,"note",`Note: ${text.trim().slice(0,80)}`);setText("");await load()};
  return(<div style={{marginTop:"18px",padding:"16px",background:"#FAFAF8",borderRadius:"10px",border:"1.5px solid #E8E5E0"}}><div style={{...ss.label,marginBottom:"12px",color:"#666"}}>Notes</div>
    {ROLES_CAN_ADD_NOTES.includes(userRole)&&orderStatus!=="Closed"&&<div style={{display:"flex",gap:"8px",marginBottom:"12px"}}><input type="text" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")add()}} placeholder="Add a note..." style={{...ss.sm,flex:1}}/><button onClick={add} disabled={!text.trim()} style={{...ss.btn,background:text.trim()?"#1a1a1a":"#ccc",color:"#fff",fontSize:"12px",padding:"6px 14px"}}>Post</button></div>}
    {ld?<div style={{fontSize:"12px",color:"#bbb"}}>Loading...</div>:notes.length===0?<div style={{fontSize:"12px",color:"#bbb",fontStyle:"italic"}}>No notes yet.</div>:<div style={{display:"flex",flexDirection:"column",gap:"6px",maxHeight:"250px",overflowY:"auto"}}>{notes.map(n=><div key={n.id} style={{padding:"8px 10px",background:"#fff",borderRadius:"6px",border:"1px solid #e8e8e5"}}><div style={{fontSize:"13px",color:"#333",whiteSpace:"pre-wrap"}}>{n.content}</div><div style={{fontSize:"10px",color:"#bbb",marginTop:"4px"}}>{n.author_name} - {new Date(n.created_at).toLocaleDateString("en-GB",{day:"numeric",month:"short"})} {new Date(n.created_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</div></div>)}</div>}</div>);
}

/* === DELIVERY === */
function DeliveryPanel({orderId,totalQty,userRole,payBalance,onDeliveryChange,orderStatus,onAutoAdvance}){
  const[batches,setBatches]=useState([]);const[ld,setLd]=useState(true);const[showForm,setShowForm]=useState(false);const[editId,setEditId]=useState(null);
  const[qty,setQty]=useState("");const[desc,setDesc]=useState("");const[loc,setLoc]=useState("");const[delBy,setDelBy]=useState("");const[recBy,setRecBy]=useState("");const[notes,setNotes]=useState("");const[authReason,setAuthReason]=useState("");
  const sb=createClient();const load=useCallback(async()=>{const{data}=await sb.from("order_deliveries").select("*").eq("order_id",orderId).order("batch_number");setBatches(data||[]);setLd(false);const t=(data||[]).reduce((s,b)=>s+(b.quantity||0),0);if(onDeliveryChange)onDeliveryChange(t)},[orderId]);
  useEffect(()=>{load()},[load]);
  const delivered=batches.reduce((s,b)=>s+(b.quantity||0),0);const remaining=Math.max((totalQty||0)-delivered,0);const pct=totalQty>0?Math.round((delivered/totalQty)*100):0;
  const needsAuth=payBalance>0;const isAdmin=userRole==="admin";const canDeliver=ROLES_CAN_DELIVER.includes(userRole);const isClosed=orderStatus==="Closed";
  const resetForm=()=>{setQty("");setDesc("");setLoc("");setDelBy("");setRecBy("");setNotes("");setAuthReason("");setShowForm(false);setEditId(null)};
  const startEdit=(b)=>{setEditId(b.id);setQty(String(b.quantity));setDesc(b.description||"");setLoc(b.delivery_location||"");setDelBy(b.delivered_by||"");setRecBy(b.received_by||"");setNotes(b.notes||"");setShowForm(true)};
  const record=async()=>{const q=parseInt(qty);if(!q||q<=0)return;const existingDel=editId?delivered-((batches.find(b=>b.id===editId)?.quantity)||0):delivered;if(totalQty>0&&(existingDel+q)>totalQty){alert(`Delivery exceeds remaining units.\nTotal: ${totalQty}\nDelivered: ${existingDel}\nRemaining: ${totalQty-existingDel}\nEntered: ${q}`);return}
    if(editId){await sb.from("order_deliveries").update({quantity:q,description:desc.trim()||null,delivery_location:loc.trim()||null,delivered_by:delBy.trim()||null,received_by:recBy.trim()||null,notes:notes.trim()||null}).eq("id",editId);await logAct(sb,orderId,"delivery_edited",`Batch edited: ${q} units${loc?" to "+loc:""}`)}
    else{const bn=(batches.length>0?Math.max(...batches.map(b=>b.batch_number)):0)+1;await sb.from("order_deliveries").insert({order_id:orderId,batch_number:bn,quantity:q,description:desc.trim()||null,delivery_location:loc.trim()||null,delivered_by:delBy.trim()||null,received_by:recBy.trim()||null,notes:notes.trim()||null,admin_authorized:needsAuth&&isAdmin,admin_auth_reason:needsAuth?authReason.trim()||null:null,payment_status_at_delivery:payBalance>0?"Balance pending":"Paid"});await logAct(sb,orderId,"delivery",`Batch ${bn}: ${q} units${loc?" to "+loc:""}${needsAuth?" [Admin auth]":""}`)}
    resetForm();await load();if(orderStatus==="Ready for Delivery"&&onAutoAdvance&&!editId){onAutoAdvance("Partially Delivered")}};
  return(<div style={{marginTop:"18px",padding:"16px",background:"#FAFAF8",borderRadius:"10px",border:"1.5px solid #E8E5E0"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}><div style={{...ss.label,marginBottom:0,color:"#666"}}>Delivery Tracking</div>{canDeliver&&!isClosed&&<button onClick={()=>{if(showForm)resetForm();else setShowForm(true)}} style={{...ss.btn,background:"#1a1a1a",color:"#fff",fontSize:"11px",padding:"5px 12px"}}>{showForm?"Cancel":"+ Record Batch"}</button>}</div>
    {totalQty>0&&<div style={{marginBottom:"14px"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:"8px",marginBottom:"8px",fontSize:"12px"}}><div style={{background:"#f5f5f3",borderRadius:"6px",padding:"8px 10px"}}><div style={{color:"#888",fontSize:"10px",fontWeight:600}}>TOTAL</div><div style={{fontWeight:700}}>{totalQty}</div></div><div style={{background:"#E8F5E9",borderRadius:"6px",padding:"8px 10px"}}><div style={{color:"#2E7D32",fontSize:"10px",fontWeight:600}}>DELIVERED</div><div style={{fontWeight:700,color:"#2E7D32"}}>{delivered}</div></div><div style={{background:remaining>0?"#FFF3E0":"#f5f5f3",borderRadius:"6px",padding:"8px 10px"}}><div style={{color:remaining>0?"#E65100":"#888",fontSize:"10px",fontWeight:600}}>REMAINING</div><div style={{fontWeight:700,color:remaining>0?"#E65100":"#999"}}>{remaining}</div></div><div style={{background:pct>=100?"#E8F5E9":"#E3F2FD",borderRadius:"6px",padding:"8px 10px"}}><div style={{color:pct>=100?"#2E7D32":"#1565C0",fontSize:"10px",fontWeight:600}}>PROGRESS</div><div style={{fontWeight:700,color:pct>=100?"#2E7D32":"#1565C0"}}>{pct}%</div></div></div><div style={{height:"8px",background:"#eee",borderRadius:"4px",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.min(pct,100)}%`,background:pct>=100?"#2E7D32":"#1565C0",borderRadius:"4px"}}/></div></div>}
    {!ld&&batches.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"4px",marginBottom:"12px"}}>{batches.map(b=><div key={b.id} style={{padding:"8px 10px",background:"#fff",borderRadius:"6px",border:"1px solid #e8e8e5",fontSize:"12px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"2px"}}><span style={{fontWeight:700}}>Batch {b.batch_number} - {b.quantity} units</span><div style={{display:"flex",gap:"6px",alignItems:"center"}}><span style={{color:"#999",fontSize:"11px"}}>{new Date(b.delivery_date).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</span>{canDeliver&&!isClosed&&<button onClick={()=>startEdit(b)} style={{background:"none",border:"1px solid #ddd",borderRadius:"4px",padding:"2px 6px",fontSize:"10px",color:"#1565C0",cursor:"pointer",fontWeight:600}}>Edit</button>}</div></div>{b.delivery_location&&<div style={{color:"#666"}}>{b.delivery_location}</div>}{b.description&&<div style={{color:"#666"}}>{b.description}</div>}{b.admin_authorized&&<div style={{fontSize:"10px",color:"#E65100",marginTop:"2px"}}>Admin authorized{b.admin_auth_reason?`: ${b.admin_auth_reason}`:""}</div>}</div>)}</div>}
    {showForm&&<div style={{background:"#fff",borderRadius:"8px",border:"1px solid #e0e0e0",padding:"14px",marginTop:"8px"}}>{needsAuth&&!isAdmin&&<div style={{padding:"10px",background:"#FCE4EC",borderRadius:"6px",marginBottom:"12px",fontSize:"12px",color:"#C62828",fontWeight:600}}>Outstanding balance. Contact Admin to authorize.</div>}
      {(canDeliver&&(!needsAuth||isAdmin))&&<div className="form-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"8px"}}><div><label style={{...ss.label,fontSize:"10px"}}>Quantity *</label><input type="number" value={qty} onChange={e=>setQty(e.target.value)} style={ss.sm} min="1"/></div><div><label style={{...ss.label,fontSize:"10px"}}>Location</label><input type="text" value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Block A" style={ss.sm}/></div><div><label style={{...ss.label,fontSize:"10px"}}>Delivered By</label><input type="text" value={delBy} onChange={e=>setDelBy(e.target.value)} style={ss.sm}/></div><div><label style={{...ss.label,fontSize:"10px"}}>Received By</label><input type="text" value={recBy} onChange={e=>setRecBy(e.target.value)} style={ss.sm}/></div><div style={{gridColumn:"1 / -1"}}><label style={{...ss.label,fontSize:"10px"}}>Description</label><input type="text" value={desc} onChange={e=>setDesc(e.target.value)} style={ss.sm}/></div>{needsAuth&&isAdmin&&<div style={{gridColumn:"1 / -1"}}><label style={{...ss.label,fontSize:"10px",color:"#E65100"}}>Authorization Reason *</label><input type="text" value={authReason} onChange={e=>setAuthReason(e.target.value)} placeholder="Reason for delivery with balance" style={ss.sm}/></div>}<div style={{gridColumn:"1 / -1"}}><button onClick={record} disabled={!parseInt(qty)||(needsAuth&&isAdmin&&!authReason.trim()&&!editId)} style={{...ss.btn,background:parseInt(qty)?"#2E7D32":"#ccc",color:"#fff",fontSize:"12px",padding:"8px 16px"}}>{editId?"Update Batch":"Record Delivery"}</button></div></div>}</div>}
  </div>);
}

/* === PAYMENTS === */
function PaymentPanel({orderId,totalValue,userRole,onPaymentChange,orderStatus}){const[payments,setPayments]=useState([]);const[ld,setLd]=useState(true);const[amt,setAmt]=useState("");const[desc,setDesc]=useState("");const[payDate,setPayDate]=useState(new Date().toISOString().split("T")[0]);const sb=createClient();
  const load=useCallback(async()=>{const{data}=await sb.from("order_payments").select("*").eq("order_id",orderId).order("payment_date");const l=data||[];setPayments(l);setLd(false);if(onPaymentChange)onPaymentChange(l.reduce((s,p)=>s+(parseFloat(p.amount)||0),0))},[orderId]);useEffect(()=>{load()},[load]);
  const add=async()=>{const a=parseFloat(amt);if(!a||a<=0||!desc.trim())return;await sb.from("order_payments").insert({order_id:orderId,amount:a,description:desc.trim(),payment_date:payDate});await logAct(sb,orderId,"payment",`Payment: KES ${a.toLocaleString()} - ${desc.trim()}`);setAmt("");setDesc("");setPayDate(new Date().toISOString().split("T")[0]);await load()};
  const del=async(p)=>{await sb.from("order_payments").delete().eq("id",p.id);await logAct(sb,orderId,"payment_deleted",`Removed: KES ${parseFloat(p.amount).toLocaleString()}`);await load()};
  const tp=payments.reduce((s,p)=>s+(parseFloat(p.amount)||0),0);const bal=(totalValue||0)-tp;const pct=totalValue>0?Math.round((tp/totalValue)*100):0;const ps=getPayStatus(tp,totalValue);const canPay=ROLES_CAN_PAY.includes(userRole);
  return(<div style={{marginTop:"18px",padding:"16px",background:"#FAFAF8",borderRadius:"10px",border:"1.5px solid #E8E5E0"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}><div style={{...ss.label,marginBottom:0,color:"#666"}}>Payments</div><Badge status={ps} type="payment"/></div>
    {totalValue>0&&<div style={{marginBottom:"14px"}}><div style={{display:"flex",justifyContent:"space-between",fontSize:"12px",color:"#666",marginBottom:"6px"}}><span>KES {tp.toLocaleString()} of KES {totalValue.toLocaleString()}</span><span style={{fontWeight:700,color:pct>=100?"#2E7D32":pct>=50?"#1565C0":"#C62828"}}>{pct}%</span></div><div style={{height:"8px",background:"#eee",borderRadius:"4px",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.min(pct,100)}%`,background:pct>=100?"#2E7D32":pct>=50?"#1565C0":"#E65100",borderRadius:"4px"}}/></div><div style={{display:"flex",justifyContent:"space-between",fontSize:"11px",color:"#999",marginTop:"4px"}}><span>Paid: KES {tp.toLocaleString()}</span><span>Balance: KES {Math.max(bal,0).toLocaleString()}</span></div></div>}
    {!ld&&payments.length>0&&<div style={{display:"flex",flexDirection:"column",gap:"4px",marginBottom:"12px"}}>{payments.map(p=><div key={p.id} style={{display:"flex",alignItems:"center",gap:"8px",padding:"6px 10px",background:"#fff",borderRadius:"6px",border:"1px solid #e8e8e5",fontSize:"12px",flexWrap:"wrap"}}><span style={{fontWeight:700,color:"#2E7D32",minWidth:"90px"}}>KES {parseFloat(p.amount).toLocaleString()}</span><span style={{flex:1,color:"#666",minWidth:"80px"}}>{p.description}</span><span style={{color:"#bbb",fontSize:"11px"}}>{new Date(p.payment_date).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</span>{userRole==="admin"&&<button onClick={()=>{if(confirm("Delete?"))del(p)}} style={{background:"none",border:"none",color:"#C62828",cursor:"pointer",fontSize:"12px",fontWeight:700}}>x</button>}</div>)}</div>}
    {canPay&&orderStatus!=="Closed"&&<div style={{display:"flex",gap:"8px",flexWrap:"wrap",alignItems:"center"}}><input type="number" placeholder="Amount" value={amt} onChange={e=>setAmt(e.target.value)} style={{...ss.sm,maxWidth:"110px"}}/><input type="text" placeholder="Description" value={desc} onChange={e=>setDesc(e.target.value)} style={{...ss.sm,flex:1,minWidth:"80px"}}/><input type="date" value={payDate} onChange={e=>setPayDate(e.target.value)} style={{...ss.sm,maxWidth:"140px"}}/><button onClick={add} disabled={!amt||!desc.trim()} style={{...ss.btn,background:amt&&desc.trim()?"#2E7D32":"#ccc",color:"#fff",fontSize:"12px",padding:"8px 14px"}}>+ Add</button></div>}
  </div>);
}

/* === DOCUMENTS === */
function DocumentsPanel({orderId,userRole}){const[docs,setDocs]=useState([]);const[ld,setLd]=useState(true);const[up,setUp]=useState(false);const[st,setSt]=useState("Invoice");const fr=useRef(null);const sb=createClient();
  const load=useCallback(async()=>{const{data}=await sb.from("order_documents").select("*").eq("order_id",orderId).order("uploaded_at",{ascending:false});setDocs(data||[]);setLd(false)},[orderId]);useEffect(()=>{load()},[load]);
  const upload=async(e)=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024){alert("Max 10MB.");return}setUp(true);try{const ext=f.name.split(".").pop();const fp=`${orderId}/${Date.now()}.${ext}`;const{error:ue}=await sb.storage.from("order-documents").upload(fp,f,{contentType:f.type});if(ue)throw ue;await sb.from("order_documents").insert({order_id:orderId,name:f.name,doc_type:st,file_path:fp,file_size:f.size,mime_type:f.type});await logAct(sb,orderId,"document",`Uploaded ${st}: ${f.name}`);await load()}catch(err){alert("Failed: "+err.message)}setUp(false);if(fr.current)fr.current.value=""};
  const view=async(d)=>{const{data}=await sb.storage.from("order-documents").createSignedUrl(d.file_path,3600);if(data?.signedUrl)window.open(data.signedUrl,"_blank")};const dl=async(d)=>{const{data}=await sb.storage.from("order-documents").download(d.file_path);if(data){const u=URL.createObjectURL(data);const a=document.createElement("a");a.href=u;a.download=d.name;a.click();URL.revokeObjectURL(u)}};const rm=async(d)=>{await sb.storage.from("order-documents").remove([d.file_path]);await sb.from("order_documents").delete().eq("id",d.id);await logAct(sb,orderId,"document_deleted",`Removed: ${d.name}`);await load()};const fs=(b)=>!b?"":b<1024?b+"B":b<1048576?(b/1024).toFixed(0)+"KB":(b/1048576).toFixed(1)+"MB";const canUp=ROLES_CAN_UPLOAD.includes(userRole);
  return(<div style={{marginTop:"18px",padding:"16px",background:"#FAFAF8",borderRadius:"10px",border:"1.5px solid #E8E5E0"}}><div style={{...ss.label,marginBottom:"12px",color:"#666"}}>Documents</div>{ld?<div style={{fontSize:"12px",color:"#bbb"}}>Loading...</div>:docs.length>0?<div style={{display:"flex",flexDirection:"column",gap:"6px",marginBottom:"14px"}}>{docs.map(d=><div key={d.id} style={{display:"flex",alignItems:"center",gap:"8px",padding:"8px 10px",background:"#fff",borderRadius:"6px",border:"1px solid #e8e8e5",flexWrap:"wrap"}}><span style={{fontSize:"16px"}}>{DOC_ICONS[d.doc_type]||"*"}</span><div style={{flex:1,minWidth:"100px"}}><div style={{fontSize:"13px",fontWeight:600,color:"#333",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{d.name}</div><div style={{fontSize:"10px",color:"#999"}}>{d.doc_type} - {fs(d.file_size)} - {new Date(d.uploaded_at).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</div></div><div style={{display:"flex",gap:"4px"}}><button onClick={()=>view(d)} style={{padding:"4px 8px",borderRadius:"4px",border:"1px solid #ddd",background:"#fff",fontSize:"11px",fontWeight:600,color:"#1565C0",cursor:"pointer"}}>View</button><button onClick={()=>dl(d)} style={{padding:"4px 8px",borderRadius:"4px",border:"1px solid #ddd",background:"#fff",fontSize:"11px",fontWeight:600,color:"#2E7D32",cursor:"pointer"}}>DL</button>{userRole==="admin"&&<button onClick={()=>{if(confirm("Remove?"))rm(d)}} style={{padding:"4px 8px",borderRadius:"4px",border:"1px solid #f0d0d0",background:"#fff",fontSize:"11px",fontWeight:600,color:"#C62828",cursor:"pointer"}}>x</button>}</div></div>)}</div>:<div style={{fontSize:"12px",color:"#bbb",padding:"4px 0 12px",fontStyle:"italic"}}>No documents.</div>}
    {canUp&&<div style={{display:"flex",gap:"8px",alignItems:"center",flexWrap:"wrap"}}><select value={st} onChange={e=>setSt(e.target.value)} style={{padding:"8px 10px",borderRadius:"6px",border:"1.5px solid #e0e0e0",fontSize:"13px",background:"#fff"}}>{DOC_TYPES.map(t=><option key={t}>{t}</option>)}</select><label style={{display:"inline-flex",alignItems:"center",gap:"5px",padding:"8px 14px",borderRadius:"6px",border:"1.5px dashed #ccc",fontSize:"13px",fontWeight:600,color:"#666",cursor:"pointer",background:"#fff"}}>{up?"Uploading...":"Upload"}<input ref={fr} type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx,.xls,.xlsx" onChange={upload} style={{display:"none"}}/></label></div>}</div>);
}

/* === ACTIVITY === */
function ActivityTimeline({orderId}){const[a,setA]=useState([]);const[l,setL]=useState(false);const sb=createClient();useEffect(()=>{(async()=>{const{data}=await sb.from("order_activities").select("*").eq("order_id",orderId).order("created_at",{ascending:false}).limit(30);setA(data||[]);setL(true)})()},[orderId]);if(!l)return null;return(<div style={{marginTop:"18px",padding:"16px",background:"#FAFAF8",borderRadius:"10px",border:"1.5px solid #E8E5E0"}}><div style={{...ss.label,marginBottom:"12px",color:"#666"}}>Activity</div>{a.length===0?<div style={{fontSize:"12px",color:"#bbb",fontStyle:"italic"}}>No activity.</div>:<div style={{display:"flex",flexDirection:"column",gap:"2px",maxHeight:"200px",overflowY:"auto"}}>{a.map(x=><div key={x.id} style={{fontSize:"12px",color:"#666",padding:"5px 0",borderBottom:"1px solid #f0f0f0",display:"flex",gap:"8px"}}><span style={{color:"#bbb",fontSize:"11px",minWidth:"65px",flexShrink:0}}>{new Date(x.created_at).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</span><span>{x.description}</span></div>)}</div>}</div>)}

/* === MODALS === */
function QuotePrompt({onConfirm,onCancel}){const[n,setN]=useState("");return(<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.5)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"16px"}}><div style={{background:"#fff",borderRadius:"12px",padding:"24px",maxWidth:"400px",width:"100%",boxShadow:"0 8px 40px rgba(0,0,0,0.2)"}}><h3 style={{fontSize:"16px",fontWeight:700,marginBottom:"16px"}}>Enter Quote Number</h3><input type="text" value={n} onChange={e=>setN(e.target.value)} placeholder="e.g. QT-001234" style={ss.input} autoFocus/><div style={{display:"flex",gap:"10px",marginTop:"18px"}}><button onClick={()=>onConfirm(n.trim())} style={{...ss.btn,background:"#1565C0",color:"#fff",flex:1}}>Save</button><button onClick={()=>onConfirm("")} style={{...ss.btn,background:"#f5f5f5",color:"#999"}}>Skip</button><button onClick={onCancel} style={{...ss.btn,background:"#f5f5f5",color:"#666"}}>Cancel</button></div></div></div>)}
function DepositPrompt({onConfirm,onCancel}){const[amt,setAmt]=useState("");const[desc,setDesc]=useState("Deposit");const[dt,setDt]=useState(new Date().toISOString().split("T")[0]);const[inv,setInv]=useState("");const v=parseFloat(amt)>0&&desc.trim();return(<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.5)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"16px"}}><div style={{background:"#fff",borderRadius:"12px",padding:"24px",maxWidth:"420px",width:"100%",boxShadow:"0 8px 40px rgba(0,0,0,0.2)"}}><h3 style={{fontSize:"16px",fontWeight:700,marginBottom:"16px"}}>Record Deposit and Invoice</h3><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div><label style={ss.label}>Invoice Number</label><input type="text" value={inv} onChange={e=>setInv(e.target.value)} placeholder="INV-001234" style={ss.input}/></div><div><label style={ss.label}>Amount (KES) *</label><input type="number" value={amt} onChange={e=>setAmt(e.target.value)} style={ss.input} autoFocus/></div><div><label style={ss.label}>Description *</label><input type="text" value={desc} onChange={e=>setDesc(e.target.value)} style={ss.input}/></div><div><label style={ss.label}>Date</label><input type="date" value={dt} onChange={e=>setDt(e.target.value)} style={ss.input}/></div></div><div style={{display:"flex",gap:"10px",marginTop:"18px"}}><button onClick={()=>v&&onConfirm({amount:parseFloat(amt),description:desc.trim(),payment_date:dt,invoice_number:inv.trim()})} disabled={!v} style={{...ss.btn,background:v?"#2E7D32":"#ccc",color:"#fff",flex:1}}>Record</button><button onClick={onCancel} style={{...ss.btn,background:"#f5f5f5",color:"#666"}}>Cancel</button></div></div></div>)}
function RepairForm({parentOrder,onConfirm,onCancel}){const[reason,setReason]=useState(REPAIR_REASONS[0]);const[type,setType]=useState("repair");const[desc,setDesc]=useState("");const[val,setVal]=useState("");return(<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.5)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"16px"}}><div style={{background:"#fff",borderRadius:"12px",padding:"24px",maxWidth:"460px",width:"100%",boxShadow:"0 8px 40px rgba(0,0,0,0.2)",maxHeight:"90vh",overflowY:"auto"}}><h3 style={{fontSize:"16px",fontWeight:700,marginBottom:"16px"}}>Create Return / Repair</h3><div style={{display:"flex",flexDirection:"column",gap:"10px"}}><div><label style={ss.label}>Type</label><select value={type} onChange={e=>setType(e.target.value)} style={ss.input}><option value="repair">Repair</option><option value="return">Return</option></select></div><div><label style={ss.label}>Reason</label><select value={reason} onChange={e=>setReason(e.target.value)} style={ss.input}>{REPAIR_REASONS.map(r=><option key={r}>{r}</option>)}</select></div><div><label style={ss.label}>Description *</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={3} style={{...ss.input,resize:"vertical"}} placeholder="What needs repair"/></div><div><label style={ss.label}>Cost (KES)</label><input type="number" value={val} onChange={e=>setVal(e.target.value)} style={ss.input}/></div></div><div style={{display:"flex",gap:"10px",marginTop:"18px"}}><button onClick={()=>desc.trim()&&onConfirm({type,reason,description:desc.trim(),value:parseFloat(val)||0})} disabled={!desc.trim()} style={{...ss.btn,background:desc.trim()?"#C62828":"#ccc",color:"#fff",flex:1}}>Create</button><button onClick={onCancel} style={{...ss.btn,background:"#f5f5f5",color:"#666"}}>Cancel</button></div></div></div>)}

/* === ORDER FORM === */
function OrderForm({onSave,onCancel,initial,userRole}){
  const FIELDS=["client","contact_person","author","items","due_date","assigned_to","notes","total_value","quote_number","invoice_number","customer_type","payment_terms","batch_delivery"];
  const defaults={client:"",contact_person:"",author:"",items:"",due_date:"",assigned_to:"",notes:"",total_value:"",quote_number:"",invoice_number:"",customer_type:"retail",payment_terms:"cash_before",batch_delivery:false};
  const initV=initial?FIELDS.reduce((a,k)=>{a[k]=initial[k]??"";return a},{}):defaults;
  const[form,setForm]=useState(initV);const[orderItems,setOrderItems]=useState([]);const[ldItems,setLdItems]=useState(false);const sb=createClient();
  const set=(k)=>(e)=>setForm({...form,[k]:e.target.value});const valid=form.client.trim()&&(orderItems.length>0||form.items?.trim());
  useEffect(()=>{if(initial?.id){(async()=>{const{data}=await sb.from("order_items").select("*").eq("order_id",initial.id).order("sort_order");if(data)setOrderItems(data.map(d=>({...d,_id:d.id})));setLdItems(true)})()}else setLdItems(true)},[initial]);
  return(<div style={{background:"#fff",borderRadius:"10px",padding:"20px",border:"1px solid #e0e0e0",marginBottom:"20px",boxShadow:"0 2px 12px rgba(0,0,0,0.06)"}}>
    <h3 style={{margin:"0 0 16px",fontSize:"16px",fontWeight:700}}>{initial?"Edit Order":"New Order"}</h3>
    <div className="form-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px"}}>
      {[{l:"Client Name *",k:"client",t:"text"},{l:"Client Contact",k:"contact_person",t:"text",p:"Name / phone / email"},{l:"Order Author",k:"author",t:"text",p:"Who owns this?"},{l:"Assigned To",k:"assigned_to",t:"text",p:"Workshop / person"},{l:"Due Date",k:"due_date",t:"date"},{l:"Order Value (KES)",k:"total_value",t:"number",p:"e.g. 150000"},{l:"Quote Number",k:"quote_number",t:"text",p:"From Manager.io"},{l:"Invoice Number",k:"invoice_number",t:"text",p:"From Manager.io"}].map(({l,k,t,p})=><div key={k}><label style={ss.label}>{l}</label><input type={t} value={form[k]||""} onChange={set(k)} placeholder={p} style={ss.input}/></div>)}
      <div><label style={ss.label}>Customer Type</label><select value={form.customer_type||"retail"} onChange={set("customer_type")} style={ss.input}>{CUSTOMER_TYPES.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></div>
      <div><label style={ss.label}>Payment Terms</label><select value={form.payment_terms||"cash_before"} onChange={set("payment_terms")} style={ss.input}>{PAYMENT_TERMS.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></div>
      {["admin","production_manager"].includes(userRole)&&<div><label style={ss.label}>Batch Delivery</label><div style={{display:"flex",alignItems:"center",gap:"8px"}}><button type="button" onClick={()=>setForm({...form,batch_delivery:!form.batch_delivery})} style={{padding:"6px 14px",borderRadius:"6px",border:"1.5px solid "+(form.batch_delivery?"#2E7D32":"#e0e0e0"),background:form.batch_delivery?"#E8F5E9":"#fff",color:form.batch_delivery?"#2E7D32":"#999",fontSize:"12px",fontWeight:600,cursor:"pointer"}}>{form.batch_delivery?"Enabled":"Disabled"}</button><span style={{fontSize:"11px",color:"#bbb"}}>For large/phased deliveries</span></div></div>}
    </div>
    <div style={{marginTop:"14px"}}>{ldItems&&<ItemsBuilder items={orderItems} onChange={setOrderItems}/>}</div>
    <div style={{marginTop:"14px"}}><label style={ss.label}>Additional Notes</label><textarea value={form.notes||""} onChange={set("notes")} rows={2} style={{...ss.input,resize:"vertical"}} placeholder="Special instructions, delivery address"/></div>
    <div style={{display:"flex",gap:"10px",marginTop:"16px"}}><button onClick={()=>valid&&onSave(form,orderItems)} disabled={!valid} style={{...ss.btn,background:valid?"#1a1a1a":"#ccc",color:"#fff"}}>{initial?"Update":"Add Order"}</button><button onClick={onCancel} style={{...ss.btn,background:"#f5f5f5",color:"#666"}}>Cancel</button></div>
  </div>);
}

/* ================================================ */
/* ============= MAIN ORDER TRACKER =============== */
/* ================================================ */
export default function OrderTracker(){
  const[orders,setOrders]=useState([]);const[loaded,setLoaded]=useState(false);const[showForm,setShowForm]=useState(false);const[editId,setEditId]=useState(null);
  const[filterStatus,setFilterStatus]=useState("All");const[filterType,setFilterType]=useState("All");const[search,setSearch]=useState("");
  const[expandedId,setExpandedId]=useState(null);const[itemSums,setItemSums]=useState({});const[docCounts,setDocCounts]=useState({});const[payTotals,setPayTotals]=useState({});const[delTotals,setDelTotals]=useState({});
  const[expItems,setExpItems]=useState([]);const[expTotalQty,setExpTotalQty]=useState(0);
  const[depositPrompt,setDepositPrompt]=useState(null);const[quotePrompt,setQuotePrompt]=useState(null);const[repairForm,setRepairForm]=useState(null);const[batchPrompt,setBatchPrompt]=useState(null);
  const[userRole,setUserRole]=useState("viewer");const[userName,setUserName]=useState("");const[adminSettings,setAdminSettings]=useState({});
  const sb=createClient();

  useEffect(()=>{(async()=>{const{data:{user}}=await sb.auth.getUser();if(user){const{data:p}=await sb.from("user_profiles").select("role,display_name").eq("id",user.id).single();if(p){setUserRole(p.role);setUserName(p.display_name||user.email?.split("@")[0]||"")}}const{data:sets}=await sb.from("admin_settings").select("*");if(sets){const s={};sets.forEach(r=>{s[r.key]=r.value});setAdminSettings(s)}})()},[]);

  const loadOrders=useCallback(async()=>{
    const{data:ord}=await sb.from("orders").select("*").order("created_at",{ascending:false});if(ord)setOrders(ord);
    const{data:items}=await sb.from("order_items").select("order_id,category,quantity");if(items){const m={};items.forEach(i=>{if(!m[i.order_id])m[i.order_id]={qty:0,cats:{}};m[i.order_id].qty+=(i.quantity||1);m[i.order_id].cats[i.category]=(m[i.order_id].cats[i.category]||0)+(i.quantity||1)});setItemSums(m)}
    const{data:docs}=await sb.from("order_documents").select("order_id");if(docs){const c={};docs.forEach(d=>{c[d.order_id]=(c[d.order_id]||0)+1});setDocCounts(c)}
    const{data:pays}=await sb.from("order_payments").select("order_id,amount");if(pays){const t={};pays.forEach(p=>{t[p.order_id]=(t[p.order_id]||0)+parseFloat(p.amount)});setPayTotals(t)}
    const{data:dels}=await sb.from("order_deliveries").select("order_id,quantity");if(dels){const t={};dels.forEach(d=>{t[d.order_id]=(t[d.order_id]||0)+(d.quantity||0)});setDelTotals(t)}
    setLoaded(true);
  },[]);
  useEffect(()=>{loadOrders()},[loadOrders]);
  const loadExpanded=useCallback(async(oid)=>{const{data:items}=await sb.from("order_items").select("*").eq("order_id",oid).order("sort_order");setExpItems(items||[]);setExpTotalQty((items||[]).reduce((s,i)=>s+(i.quantity||1),0))},[]);
  useEffect(()=>{setExpItems([]);setExpTotalQty(0);if(expandedId)loadExpanded(expandedId)},[expandedId,loadExpanded]);

  const saveItems=async(oid,items)=>{await sb.from("order_items").delete().eq("order_id",oid);if(items.length>0){const rows=items.map((i,idx)=>({order_id:oid,category:i.category,description:i.description||null,quantity:parseInt(i.quantity)||1,size:i.size||null,finish_type:i.finish_type||null,finish_color:i.finish_color||null,wood_type:i.wood_type||null,unit_price:parseFloat(i.unit_price)||0,notes:i.notes||null,sort_order:idx}));await sb.from("order_items").insert(rows)}};

  const addOrder=async(form,items)=>{
    const summary=items.length>0?items.map(i=>`${i.quantity}x ${i.category}${i.size?" - "+i.size:""}`).join("\n"):form.items||"";
    const payload={...form,due_date:form.due_date||null,total_value:parseFloat(form.total_value)||0,status:"Inquiry",items:summary,quote_number:form.quote_number||null,invoice_number:form.invoice_number||null,customer_type:form.customer_type||"retail",payment_terms:form.payment_terms||"cash_before",batch_delivery:form.batch_delivery||false};
    delete payload.order_num;
    const{data:created,error}=await sb.from("orders").insert(payload).select().single();
    if(error){alert("Error: "+error.message);return}
    if(created){await saveItems(created.id,items);await logAct(sb,created.id,"created",`Order ${created.order_num} created for ${form.client}`)}
    await loadOrders();setShowForm(false);
    if(created&&!payload.batch_delivery){const tq=items.reduce((s,i)=>s+(parseInt(i.quantity)||1),0);const ut=parseInt(adminSettings.batch_delivery_unit_threshold)||20;const vt=parseInt(adminSettings.batch_delivery_value_threshold)||500000;if(tq>ut||(parseFloat(payload.total_value)||0)>vt){setBatchPrompt(created.id)}}
  };

  const updateOrder=async(form,items)=>{
    const old=orders.find(o=>o.id===editId);const summary=items.length>0?items.map(i=>`${i.quantity}x ${i.category}${i.size?" - "+i.size:""}`).join("\n"):form.items||old?.items||"";
    const payload={...form,due_date:form.due_date||null,total_value:parseFloat(form.total_value)||0,items:summary,quote_number:form.quote_number||null,invoice_number:form.invoice_number||null,customer_type:form.customer_type||"retail",payment_terms:form.payment_terms||"cash_before",batch_delivery:form.batch_delivery||false};
    delete payload.status;const{error}=await sb.from("orders").update(payload).eq("id",editId);if(error){alert("Error: "+error.message);return}
    await saveItems(editId,items);await logAct(sb,editId,"edited","Order updated");await loadOrders();setEditId(null);
  };

  const advanceStatus=async(id,oldSt,newSt)=>{
    const order=orders.find(o=>o.id===id);const tp=payTotals[id]||0;const tv=parseFloat(order?.total_value)||0;
    const totalQty=itemSums[id]?.qty||order?.deliverable_units||0;const totalDel=delTotals[id]||0;
    const sList=getStatusList(order?.order_type);
    if(userRole==="sales"&&sList.indexOf(newSt)>sList.indexOf(SALES_MAX_ADVANCE_TO)){alert("Sales users can only advance orders up to Deposit Paid.");return}
    if(newSt==="Quote Approved"&&!order.quote_number){setQuotePrompt({orderId:id,oldStatus:oldSt});return}
    if(newSt==="Deposit Paid"&&tp<=0){setDepositPrompt({orderId:id,oldStatus:oldSt});return}
    if(newSt==="Delivered"&&order?.batch_delivery&&totalQty>0&&totalDel<totalQty){alert(`Delivery not complete.\nDelivered: ${totalDel} of ${totalQty}\nRemaining: ${totalQty-totalDel}`);return}
    if(newSt==="Closed"){if(order?.batch_delivery&&totalQty>0&&totalDel<totalQty){alert(`Cannot close. Delivery: ${totalDel}/${totalQty}`);return}if(tv>0&&tp<tv){alert(`Cannot close. Balance: KES ${(tv-tp).toLocaleString()}`);return}}
    await sb.from("orders").update({status:newSt}).eq("id",id);await logAct(sb,id,"status_change",`Status: ${oldSt} -> ${newSt}`,oldSt,newSt);
    setOrders(p=>p.map(o=>o.id===id?{...o,status:newSt}:o));
  };

  const handleQuoteConfirm=async(q)=>{const{orderId,oldStatus}=quotePrompt;if(q)await sb.from("orders").update({quote_number:q}).eq("id",orderId);await sb.from("orders").update({status:"Quote Approved"}).eq("id",orderId);await logAct(sb,orderId,"status_change",`${oldStatus} -> Quote Approved${q?" (Q: "+q+")":""}`,oldStatus,"Quote Approved");setQuotePrompt(null);await loadOrders()};
  const handleDepositConfirm=async(d)=>{const{orderId,oldStatus}=depositPrompt;if(d.invoice_number)await sb.from("orders").update({invoice_number:d.invoice_number}).eq("id",orderId);await sb.from("order_payments").insert({order_id:orderId,amount:d.amount,description:d.description,payment_date:d.payment_date});await logAct(sb,orderId,"payment",`Deposit: KES ${d.amount.toLocaleString()}`);await sb.from("orders").update({status:"Deposit Paid"}).eq("id",orderId);await logAct(sb,orderId,"status_change",`${oldStatus} -> Deposit Paid`,oldStatus,"Deposit Paid");setDepositPrompt(null);await loadOrders()};
  const handleRepairConfirm=async(d)=>{const p=repairForm;const payload={client:p.client,contact_person:p.contact_person,author:p.author,items:d.description,status:"Reported",order_type:d.type,parent_order_id:p.id,repair_reason:d.reason,total_value:d.value,assigned_to:p.assigned_to,notes:`${d.type.toUpperCase()} for ${p.order_num}`,quote_number:p.quote_number,invoice_number:p.invoice_number};const{data:created,error}=await sb.from("orders").insert(payload).select().single();if(error){alert("Error: "+error.message);setRepairForm(null);return}if(created){await logAct(sb,created.id,"created",`${d.type} created - ${d.reason}`);await logAct(sb,p.id,"repair_created",`${d.type} ${created.order_num} created`)}setRepairForm(null);await loadOrders()};
  const deleteOrder=async(id)=>{if(userRole!=="admin"){alert("Only admins can delete.");return}const{data:docs}=await sb.from("order_documents").select("file_path").eq("order_id",id);if(docs?.length)await sb.storage.from("order-documents").remove(docs.map(d=>d.file_path));await sb.from("orders").delete().eq("id",id);await loadOrders();setExpandedId(null)};

  const filtered=orders.filter(o=>{if(filterStatus!=="All"&&o.status!==filterStatus)return false;if(filterType==="standard"&&(o.order_type==="repair"||o.order_type==="return"))return false;if(filterType==="repairs"&&o.order_type!=="repair"&&o.order_type!=="return")return false;if(search){const q=search.toLowerCase();return[o.client,o.items,o.order_num,o.assigned_to,o.author,o.contact_person,o.notes,o.quote_number,o.invoice_number].filter(Boolean).join(" ").toLowerCase().includes(q)}return true});
  const allSt=[...new Set([...STATUSES,...REPAIR_STATUSES])];const stCounts=allSt.reduce((a,s)=>{a[s]=orders.filter(o=>o.status===s).length;return a},{});
  const canCreate=ROLES_CAN_CREATE.includes(userRole);const canEdit=ROLES_CAN_EDIT.includes(userRole);const canAdvance=ROLES_CAN_ADVANCE.includes(userRole);

  if(!loaded)return <div style={{padding:"40px",textAlign:"center",color:"#aaa"}}>Loading...</div>;

  return(<div>
    {quotePrompt&&<QuotePrompt onConfirm={handleQuoteConfirm} onCancel={()=>setQuotePrompt(null)}/>}
    {depositPrompt&&<DepositPrompt onConfirm={handleDepositConfirm} onCancel={()=>setDepositPrompt(null)}/>}
    {repairForm&&<RepairForm parentOrder={repairForm} onConfirm={handleRepairConfirm} onCancel={()=>setRepairForm(null)}/>}
    {batchPrompt&&<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,0.5)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:"16px"}}><div style={{background:"#fff",borderRadius:"12px",padding:"24px",maxWidth:"400px",width:"100%",boxShadow:"0 8px 40px rgba(0,0,0,0.2)"}}><h3 style={{fontSize:"16px",fontWeight:700,marginBottom:"16px"}}>Enable Batch Delivery?</h3><p style={{fontSize:"12px",color:"#888",marginBottom:"16px"}}>This order exceeds the threshold. Enable batch delivery for hotel, bulk, or multi-phase projects.</p><div style={{display:"flex",gap:"10px"}}><button onClick={async()=>{await sb.from("orders").update({batch_delivery:true}).eq("id",batchPrompt);await loadOrders();setBatchPrompt(null)}} style={{...ss.btn,background:"#2E7D32",color:"#fff",flex:1}}>Yes, Enable</button><button onClick={()=>setBatchPrompt(null)} style={{...ss.btn,background:"#f5f5f5",color:"#666",flex:1}}>No</button></div></div></div>}

    <div style={{padding:"20px 16px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"10px"}}><div><div style={{fontSize:"24px",fontWeight:800,letterSpacing:"-0.5px"}}>Orders</div><div style={{fontSize:"12px",color:"#999"}}>{orders.length} total - {orders.filter(o=>!["Delivered","Closed","Redelivered"].includes(o.status)).length} active</div></div>{canCreate&&<button onClick={()=>{setShowForm(true);setEditId(null)}} style={{...ss.btn,background:"#E8512A",color:"#fff",padding:"11px 24px",fontWeight:700,borderRadius:"8px",fontSize:"14px",boxShadow:"0 2px 8px rgba(232,81,42,0.3)"}}>+ New Order</button>}</div>

    <div style={{display:"flex",gap:"6px",padding:"0 16px 12px",overflowX:"auto",WebkitOverflowScrolling:"touch"}}>{allSt.filter(s=>stCounts[s]>0||STATUSES.includes(s)).map(s=><div key={s} onClick={()=>setFilterStatus(filterStatus===s?"All":s)} style={{padding:"5px 10px",borderRadius:"6px",cursor:"pointer",flexShrink:0,background:filterStatus===s?(ALL_STATUS_COLORS[s]?.bg||"#eee"):"#fff",border:`1.5px solid ${filterStatus===s?(ALL_STATUS_COLORS[s]?.border||"#ccc"):"#e0e0e0"}`,fontSize:"11px",whiteSpace:"nowrap"}}><span style={{fontWeight:700,color:ALL_STATUS_COLORS[s]?.text||"#333",fontFamily:"'DM Mono',monospace"}}>{stCounts[s]||0}</span><span style={{color:"#888",marginLeft:"4px"}}>{s}</span></div>)}</div>

    <div style={{padding:"0 16px 20px"}}>
      <div style={{display:"flex",gap:"8px",marginBottom:"14px",flexWrap:"wrap"}}><input type="text" placeholder="Search client, quote, invoice..." value={search} onChange={e=>setSearch(e.target.value)} style={{...ss.input,flex:1,minWidth:"180px",maxWidth:"320px",background:"#fff"}}/><select value={filterType} onChange={e=>setFilterType(e.target.value)} style={{...ss.input,maxWidth:"150px",background:"#fff"}}><option value="All">All Types</option><option value="standard">Orders</option><option value="repairs">Repairs</option></select>{(filterStatus!=="All"||filterType!=="All"||search)&&<button onClick={()=>{setFilterStatus("All");setFilterType("All");setSearch("")}} style={{...ss.btn,background:"#fff",color:"#999",border:"1.5px solid #e0e0e0",fontSize:"12px",padding:"8px 12px"}}>Clear</button>}</div>

      {showForm&&canCreate&&<OrderForm onSave={addOrder} onCancel={()=>setShowForm(false)} userRole={userRole}/>}
      {editId&&canEdit&&<OrderForm initial={orders.find(o=>o.id===editId)} onSave={updateOrder} onCancel={()=>setEditId(null)} userRole={userRole}/>}

      {filtered.length===0?<div style={{textAlign:"center",padding:"60px 20px",color:"#bbb",background:"#fff",borderRadius:"10px",border:"1px solid #e8e8e5"}}><div style={{fontSize:"36px",marginBottom:"10px"}}>O</div><div style={{fontSize:"14px",fontWeight:600,color:"#999"}}>{orders.length===0?"No orders yet":"No match"}</div></div>:(
        <div style={{display:"flex",flexDirection:"column",gap:"8px"}}>
          {filtered.map(order=>{
            const expanded=expandedId===order.id;const days=order.due_date?Math.ceil((new Date(order.due_date+"T12:00:00")-new Date())/86400000):null;
            const overdue=days!==null&&days<0&&!["Delivered","Closed","Redelivered"].includes(order.status);
            const tp=payTotals[order.id]||0;const tv=parseFloat(order.total_value)||0;const ps=getPayStatus(tp,tv);const pct=tv>0?Math.round((tp/tv)*100):0;const bal=tv-tp;
            const iS=itemSums[order.id];const totalQty=iS?.qty||order.deliverable_units||0;const totalDel=delTotals[order.id]||0;const delPct=totalQty>0?Math.round((totalDel/totalQty)*100):0;
            const sList=getStatusList(order.order_type);const cIdx=sList.indexOf(order.status);const nextSt=cIdx<sList.length-1?sList[cIdx+1]:null;
            const isRepair=order.order_type==="repair"||order.order_type==="return";
            const showDelivery=DELIVERY_VISIBLE_FROM.includes(order.status)&&!isRepair&&order.batch_delivery;
            const children=orders.filter(o=>o.parent_order_id===order.id);const parentOrd=order.parent_order_id?orders.find(o=>o.id===order.parent_order_id):null;

            const borderClass=STATUS_BORDER_CLASS[order.status]||"";return(<div key={order.id} className={`order-card ${borderClass}`} style={{background:"#fff",borderRadius:"10px",border:`1.5px solid ${overdue?"#ef9a9a":"#e0ddd8"}`,overflow:"hidden",boxShadow:expanded?"var(--shadow-lg)":"var(--shadow-sm)"}}>
              <div onClick={()=>setExpandedId(expanded?null:order.id)} style={{padding:"12px 16px",cursor:"pointer"}}>
                <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"6px",flexWrap:"wrap",gap:"4px"}}>
                  <div style={{display:"flex",gap:"6px",alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:"12px",fontFamily:"'DM Mono',monospace",color:"#888",fontWeight:500,background:"#f0ede8",padding:"2px 6px",borderRadius:"4px"}}>{order.order_num}</span>{isRepair&&<span style={{fontSize:"9px",fontWeight:700,color:"#C62828",background:"#FCE4EC",padding:"2px 6px",borderRadius:"3px",textTransform:"uppercase"}}>{order.order_type}</span>}{order.customer_type&&order.customer_type!=="retail"&&<span style={{fontSize:"9px",fontWeight:700,color:order.customer_type==="reseller"?"#7B1FA2":"#1565C0",background:order.customer_type==="reseller"?"#F3E5F5":"#E3F2FD",padding:"2px 6px",borderRadius:"3px",textTransform:"uppercase"}}>{order.customer_type}</span>}{order.quote_number&&<span style={{fontSize:"10px",color:"#1565C0",background:"#E3F2FD",padding:"1px 5px",borderRadius:"3px"}}>Q:{order.quote_number}</span>}{order.invoice_number&&<span style={{fontSize:"10px",color:"#512DA8",background:"#EDE7F6",padding:"1px 5px",borderRadius:"3px"}}>I:{order.invoice_number}</span>}</div>
                  <div style={{display:"flex",gap:"4px",alignItems:"center",flexWrap:"wrap"}}><Badge status={order.status}/>{tv>0&&<Badge status={ps} type="payment"/>}</div>
                </div>
                <div style={{fontSize:"16px",fontWeight:700,color:overdue?"#DC2626":"#111",marginBottom:"4px",letterSpacing:"-0.3px"}}>{order.client}{docCounts[order.id]&&<span style={{fontSize:"10px",color:"#2E7D32",marginLeft:"6px"}}>{docCounts[order.id]} docs</span>}{children.length>0&&<span style={{fontSize:"10px",color:"#E65100",marginLeft:"6px"}}>{children.length} repairs</span>}</div>
                {iS?<div style={{fontSize:"12px",color:"#666",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{Object.entries(iS.cats).map(([c,q])=>`${q}x ${c}`).join(" - ")}</div>:<div style={{fontSize:"12px",color:"#999",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{order.items}</div>}
                {order.notes&&<div style={{fontSize:"11px",color:"#E65100",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginTop:"2px"}}>! {order.notes}</div>}
                <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"6px",fontSize:"11px",marginTop:"4px"}}><div style={{display:"flex",gap:"12px",color:"#888"}}>{tv>0&&<span><strong style={{color:"#333"}}>{pct}%</strong> paid - Bal: KES {Math.max(bal,0).toLocaleString()}</span>}{showDelivery&&totalQty>0&&<span>{delPct}% delivered ({totalDel}/{totalQty})</span>}{order.author&&<span>by {order.author}</span>}</div><div style={{color:overdue?"#C62828":"#999",fontWeight:overdue?700:400}}>{order.due_date?<>{new Date(order.due_date+"T12:00:00").toLocaleDateString("en-GB",{day:"numeric",month:"short"})}{overdue&&` - ${Math.abs(days)}d late`}</>:""}</div></div>
              </div>

              {expanded&&(<div style={{padding:"0 16px 16px",borderTop:"1px solid #f0f0f0"}}>
                <div className="detail-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginTop:"14px"}}>{[{l:"Author",v:order.author},{l:"Client Contact",v:order.contact_person},{l:"Assigned To",v:order.assigned_to},{l:"Created",v:new Date(order.created_at).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})},{l:"Order Value",v:tv?`KES ${tv.toLocaleString()}`:"Not set"},{l:"Due Date",v:order.due_date?new Date(order.due_date+"T12:00:00").toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"}):"Not set"},{l:"Quote #",v:order.quote_number},{l:"Invoice #",v:order.invoice_number},{l:"Customer Type",v:CUSTOMER_TYPES.find(c=>c.id===order.customer_type)?.label||"Retail"},{l:"Payment Terms",v:PAYMENT_TERMS.find(p=>p.id===order.payment_terms)?.label||"-"},{l:"Batch Delivery",v:order.batch_delivery?"Enabled":"Standard"}].map(({l,v})=><div key={l}><div style={ss.label}>{l}</div><div style={{fontSize:"13px",color:"#333",marginTop:"2px"}}>{v||"-"}</div></div>)}{isRepair&&<div><div style={ss.label}>Repair Reason</div><div style={{fontSize:"13px",color:"#C62828",marginTop:"2px",fontWeight:600}}>{order.repair_reason||"-"}</div></div>}</div>

                {(parentOrd||children.length>0)&&<div style={{marginTop:"14px",padding:"12px",background:"#FFF8E1",borderRadius:"8px",border:"1px solid #FFD54F"}}><div style={{...ss.label,color:"#F57F17",marginBottom:"6px"}}>Linked Orders</div>{parentOrd&&<div style={{fontSize:"12px",color:"#333"}}>Original: <strong>{parentOrd.order_num}</strong> - {parentOrd.client}</div>}{children.map(c=><div key={c.id} style={{fontSize:"12px",color:"#333",padding:"2px 0"}}><span style={{fontSize:"10px",fontWeight:700,color:"#C62828",background:"#FCE4EC",padding:"1px 5px",borderRadius:"3px",textTransform:"uppercase",marginRight:"4px"}}>{c.order_type}</span><strong>{c.order_num}</strong> - {c.repair_reason} <Badge status={c.status}/></div>)}</div>}

                <ItemsTable items={expItems}/>
                {order.items&&!expItems.length&&<div style={{marginTop:"14px"}}><div style={ss.label}>Items</div><TruncText text={order.items} lines={3}/></div>}
                {order.notes&&<div style={{marginTop:"12px"}}><div style={ss.label}>Special Requests</div><TruncText text={order.notes} lines={3}/></div>}

                <div style={{marginTop:"16px"}}><div style={ss.label}>Workflow{isRepair?" (Repair)":""}</div>
                  <div style={{display:"flex",gap:"2px",marginTop:"6px",marginBottom:"10px"}}>{sList.map((s,i)=><div key={s} style={{flex:1,height:"6px",borderRadius:"3px",background:i<=cIdx?(ALL_STATUS_COLORS[s]?.text||"#333"):"#e8e8e5"}} title={s}/>)}</div>
                  <div style={{display:"flex",alignItems:"center",gap:"8px",flexWrap:"wrap"}}><Badge status={order.status}/>{canAdvance&&nextSt&&order.status!=="Closed"&&!(userRole==="sales"&&sList.indexOf(nextSt)>sList.indexOf(SALES_MAX_ADVANCE_TO))?<button onClick={()=>advanceStatus(order.id,order.status,nextSt)} style={{...ss.btn,background:"#1a1a1a",color:"#fff",fontSize:"12px",padding:"7px 14px"}}>Next: {nextSt}</button>:!nextSt&&<span style={{fontSize:"12px",color:"#2E7D32",fontWeight:600}}>Complete</span>}</div>
                </div>

                {showDelivery&&<DeliveryPanel orderId={order.id} totalQty={expTotalQty||order.deliverable_units||0} userRole={userRole} payBalance={Math.max(bal,0)} onDeliveryChange={(d)=>setDelTotals(p=>({...p,[order.id]:d}))} orderStatus={order.status} onAutoAdvance={async(newSt)=>{await sb.from("orders").update({status:newSt}).eq("id",order.id);await logAct(sb,order.id,"status_change",`${order.status} -> ${newSt} (auto)`,order.status,newSt);setOrders(p=>p.map(o=>o.id===order.id?{...o,status:newSt}:o))}}/>}
                <PaymentPanel orderId={order.id} totalValue={tv} userRole={userRole} orderStatus={order.status} onPaymentChange={(t)=>setPayTotals(p=>({...p,[order.id]:t}))}/>
                <DocumentsPanel orderId={order.id} userRole={userRole}/>
                <NotesThread orderId={order.id} userRole={userRole} userName={userName} orderStatus={order.status}/>
                <ActivityTimeline orderId={order.id}/>

                <div style={{display:"flex",gap:"8px",marginTop:"16px",flexWrap:"wrap"}}>
                  {order.status==="Closed"&&<div style={{padding:"10px 14px",background:"#F5F5F5",borderRadius:"6px",fontSize:"12px",color:"#999",fontWeight:600,textAlign:"center",width:"100%"}}>Order Archived - Read Only</div>}
                  {order.status!=="Closed"&&canEdit&&<button onClick={e=>{e.stopPropagation();setEditId(order.id);setExpandedId(null)}} style={{...ss.btn,background:"#f5f5f5",color:"#333",fontSize:"12px",padding:"8px 16px"}}>Edit</button>}
                  {order.status==="Delivered"&&!isRepair&&ROLES_CAN_REPAIR.includes(userRole)&&<button onClick={e=>{e.stopPropagation();setRepairForm(order)}} style={{...ss.btn,background:"#FFF3E0",color:"#E65100",border:"1px solid #FFB74D",fontSize:"12px",padding:"8px 16px"}}>Return / Repair</button>}
                  {order.status!=="Closed"&&userRole==="admin"&&<button onClick={e=>{e.stopPropagation();if(confirm("Delete permanently?"))deleteOrder(order.id)}} style={{...ss.btn,background:"#fff",color:"#C62828",border:"1px solid #ef9a9a",fontSize:"12px",padding:"8px 16px"}}>Delete</button>}
                </div>
              </div>)}
            </div>);
          })}
        </div>
      )}
    </div>
    <style>{`
@media(max-width:640px){.form-grid,.detail-grid{grid-template-columns:1fr!important}.items-table{display:none!important}.items-cards{display:flex!important}}
@media(min-width:641px){.items-cards{display:none!important}}
    `}</style>
  </div>);
}
